final MEDIUM_PERCENTAGE_GAP = 0.03;
final SMALL_PERCENTAGE_GAP = 0.01;

final BIG_PERCENTAGE_OFFSET = 0.8;
final MEDIUM_PERCENTAGE_OFFSET = 0.7;
final SMALL_PERCENTAGE_OFFSET = 0.6;

final BIG_PERCENTAGE_HEIGHT = 0.1;
final MEDIUM_PERCENTAGE_HEIGHT = 0.08;
final SMALL_PERCENTAGE_HEIGHT = 0.06;

final FONT_SIZE_1 = 12.0;
final FONT_SIZE_2 = 16.0;
final FONT_SIZE_3 = 24.0;
final FONT_SIZE_4 = 32.0;